#!/usr/bin/env node

import { readFileSync, readdirSync, unlinkSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(fileURLToPath(new URL("..", import.meta.url)));
const CATALOG_PATH = resolve(ROOT, "roles/catalog.json");
const GENERATED_NOTE = "Generated by `npm run roles:generate` from `roles/catalog.json`; do not edit this file directly.";
const ADAPTERS = ["pi", "claude"];

function fail(message) {
  throw new Error(`roles: ${message}`);
}

function readCatalog() {
  const catalog = JSON.parse(readFileSync(CATALOG_PATH, "utf8"));
  if (catalog.schemaVersion !== 1 || !Array.isArray(catalog.roles)) fail("unsupported catalog shape");

  const names = new Set();
  const paths = new Set();
  for (const role of catalog.roles) {
    if (!/^[a-z][a-z0-9_-]*$/.test(role?.name) || names.has(role.name)) {
      fail(`invalid or duplicate role name: ${role?.name}`);
    }
    names.add(role.name);
    for (const adapter of Object.keys(role.adapters ?? {})) {
      if (!ADAPTERS.includes(adapter)) fail(`unknown adapter '${adapter}' on '${role.name}'`);
      const definition = role.adapters[adapter];
      const root = adapter === "pi" ? "agents/" : "claude-plugin/agents/";
      const expectedPath = `${root}${role.name}.md`;
      if (definition?.path !== expectedPath || paths.has(definition.path)) {
        fail(`invalid or duplicate output path: ${definition?.path}; expected ${expectedPath}`);
      }
      paths.add(definition.path);
      const fields = parseFrontmatter(definition.frontmatter);
      if (fields.name !== role.name) fail(`${definition.path} must declare name: ${role.name}`);
      if (typeof definition.prompt !== "string" || !definition.prompt.trim()) fail(`${definition.path} has no prompt`);
    }
  }
  return catalog;
}

function parseFrontmatter(text) {
  const fields = {};
  for (const line of text.split("\n")) {
    const match = line.match(/^([^:#][^:]*):\s*(.*)$/);
    if (match) fields[match[1].trim().toLowerCase()] = match[2].trim();
  }
  return fields;
}

function renderRole(definition) {
  return `---\n# ${GENERATED_NOTE}\n${definition.frontmatter}\n---\n\n${definition.prompt.trimEnd()}\n`;
}

function roleRows(catalog, adapter) {
  return catalog.roles.flatMap((role) => {
    const definition = role.adapters?.[adapter];
    if (!definition) return [];
    const fields = parseFrontmatter(definition.frontmatter);
    if (adapter === "pi") {
      return [`| \`${role.name}\` | ${fields.model || "parent model"} | ${definition.toolsSummary} | ${role.summary} |`];
    }
    return [`| \`${role.name}\` | ${fields.model || "default"} | ${fields.effort || "default"} | \`${fields.tools || "default"}\` | ${role.summary} |`];
  });
}

function generatedBlock(name, content) {
  return `<!-- BEGIN GENERATED: ${name} -->\n<!-- ${GENERATED_NOTE} -->\n${content}\n<!-- END GENERATED: ${name} -->`;
}

function replaceBlock(text, name, content) {
  const start = `<!-- BEGIN GENERATED: ${name} -->`;
  const end = `<!-- END GENERATED: ${name} -->`;
  const startIndex = text.indexOf(start);
  const endIndex = text.indexOf(end);
  const unique = startIndex >= 0
    && endIndex > startIndex
    && text.indexOf(start, startIndex + start.length) < 0
    && text.indexOf(end, endIndex + end.length) < 0;
  if (!unique) fail(`documentation must contain exactly one ordered '${name}' marker pair`);
  return text.slice(0, startIndex) + generatedBlock(name, content) + text.slice(endIndex + end.length);
}

function expectedOutputs(catalog) {
  const outputs = new Map();
  for (const role of catalog.roles) {
    for (const adapter of ADAPTERS) {
      const definition = role.adapters?.[adapter];
      if (definition) outputs.set(definition.path, renderRole(definition));
    }
  }

  let readme = readFileSync(resolve(ROOT, "README.md"), "utf8").replaceAll("\r\n", "\n");
  const piTable = [
    "| Role | Model | Tools | Purpose |",
    "| --- | --- | --- | --- |",
    ...roleRows(catalog, "pi"),
  ].join("\n");
  const claudeTable = [
    "| Role | Model | Effort | Tools | Purpose |",
    "| --- | --- | --- | --- | --- |",
    ...roleRows(catalog, "claude"),
  ].join("\n");
  readme = replaceBlock(readme, "pi-role-table", piTable);
  readme = replaceBlock(readme, "claude-role-table", claudeTable);
  outputs.set("README.md", readme);

  const skillPath = "claude-plugin/skills/herdr-subagents/SKILL.md";
  let skill = readFileSync(resolve(ROOT, skillPath), "utf8").replaceAll("\r\n", "\n");
  const skillTable = [
    "| Role | For | Model | Effort |",
    "| --- | --- | --- | --- |",
    ...catalog.roles.flatMap((role) => {
      const definition = role.adapters?.claude;
      if (!definition) return [];
      const fields = parseFrontmatter(definition.frontmatter);
      return [`| \`${role.name}\` | ${definition.skillPurpose} | ${fields.model || "default"} | ${fields.effort || "default"} |`];
    }),
  ].join("\n");
  skill = replaceBlock(skill, "claude-skill-role-table", skillTable);
  outputs.set(skillPath, skill);
  return outputs;
}

function main() {
  const command = process.argv[2];
  if (command !== "generate" && command !== "check") {
    console.error("usage: node scripts/roles.mjs generate|check");
    process.exit(2);
  }

  const outputs = expectedOutputs(readCatalog());
  const stale = [];
  for (const [relativePath, expected] of outputs) {
    const path = resolve(ROOT, relativePath);
    let actual;
    try {
      actual = readFileSync(path, "utf8").replaceAll("\r\n", "\n");
    } catch (error) {
      if (error?.code !== "ENOENT") throw error;
    }
    if (actual === expected) continue;
    stale.push(relativePath);
    if (command === "generate") writeFileSync(path, expected);
  }

  const expectedRolePaths = new Set(
    [...outputs.keys()].filter((path) => path.startsWith("agents/") || path.startsWith("claude-plugin/agents/")),
  );
  for (const dir of ["agents", "claude-plugin/agents"]) {
    for (const file of readdirSync(resolve(ROOT, dir)).filter((name) => name.endsWith(".md"))) {
      const relativePath = `${dir}/${file}`;
      if (expectedRolePaths.has(relativePath)) continue;
      stale.push(relativePath);
      if (command === "generate") unlinkSync(resolve(ROOT, relativePath));
    }
  }

  if (command === "check" && stale.length) {
    console.error(`Generated role outputs are stale:\n${stale.map((path) => `  - ${path}`).join("\n")}\nRun: npm run roles:generate`);
    process.exit(1);
  }
  if (command === "generate") console.log(`Updated ${stale.length} generated role output(s).`);
}

main();
